"""Shared reading and parsing for the increment data.

Both the manifest generator and the validator import this, so the rules for
"what is a category file" and "what is a valid value" are defined exactly once.
The browser applies the same rules in assets/benson.js; tools/check_parity.mjs
asserts that the two implementations agree on every value in the data set.
"""
from __future__ import annotations

import csv
import glob
import os
import re
from dataclasses import dataclass, field

CSV_DIR = "CSV_data_files"
MANIFEST_NAME = "manifest.json"

# 01_CH_Groups.csv -> ordering prefix, then the category name.
FILENAME_RE = re.compile(r"^(\d{2})_([A-Za-z0-9_]+)\.csv$")

NUMBER_RE = re.compile(r"^-?\d*\.?\d+$")
# "1.05-1.76" is a published range and is averaged. The dash is only a range
# separator between two numbers, so a leading minus stays a negative number.
RANGE_RE = re.compile(r"^(-?\d*\.?\d+)\s*-\s*(-?\d*\.?\d+)$")


class ValueError_(ValueError):
    """A cell that is neither a number nor a range."""


def parse_value(raw: str) -> float:
    """Turn a cell into kJ/mol. Ranges are averaged; negatives are preserved."""
    text = str(raw).strip().strip('"')
    if not text:
        raise ValueError_("empty value")
    match = RANGE_RE.match(text)
    if match:
        return (float(match.group(1)) + float(match.group(2))) / 2
    if NUMBER_RE.match(text):
        return float(text)
    raise ValueError_(f"{text!r} is neither a number nor a range like 1.05-1.76")


def title_for(stem: str) -> str:
    """01_CH_Groups -> 'CH Groups'.

    The casing a contributor writes in the filename is the casing shown in the
    tab, so no list of chemical acronyms has to live in the code: CH stays CH
    because it was already written that way.
    """
    match = FILENAME_RE.match(stem + ".csv")
    name = match.group(2) if match else stem
    return " ".join(name.split("_"))


@dataclass
class Category:
    """One CSV file: its identity on disk and the rows it holds."""

    path: str
    columns: list[str] = field(default_factory=list)
    rows: list[tuple[str, str]] = field(default_factory=list)

    @property
    def file(self) -> str:
        return os.path.basename(self.path)

    @property
    def stem(self) -> str:
        return self.file[:-4]

    @property
    def title(self) -> str:
        return title_for(self.stem)

    @property
    def has_valid_name(self) -> bool:
        return FILENAME_RE.match(self.file) is not None


def read_category(path: str) -> Category:
    """Read one CSV without judging it: validation is validate_data.py's job."""
    with open(path, encoding="utf-8-sig", newline="") as handle:
        raw = list(csv.reader(handle))
    if not raw:
        return Category(path=path)
    header = [c.strip() for c in raw[0]]
    rows = [tuple(c.strip() for c in row[:2]) for row in raw[1:] if row and row[0].strip()]
    return Category(path=path, columns=header, rows=rows)


def find_categories(csv_dir: str = CSV_DIR) -> list[Category]:
    """Every CSV in the folder, ordered by filename so the numeric prefix works."""
    return [read_category(p) for p in sorted(glob.glob(os.path.join(csv_dir, "*.csv")))]


def manifest_for(categories: list[Category]) -> dict:
    """The category index the site reads in place of scanning the folder."""
    return {
        "_comment": "Generated by tools/build_data.py - do not edit by hand.",
        "categories": [
            {
                "file": category.file,
                "title": category.title,
                "columns": category.columns,
                "count": len(category.rows),
            }
            for category in categories
        ],
    }


def build_manifest_comparable(source: list[Category] | dict) -> list[tuple]:
    """Normalise a manifest - built or committed - so the two can be compared."""
    entries = manifest_for(source)["categories"] if isinstance(source, list) else source.get("categories", [])
    return [
        (e.get("file"), e.get("title"), tuple(e.get("columns") or ()), e.get("count"))
        for e in entries
    ]
